### ISSUE TITLE
Deploy site to GitHub pages

### ISSUE THREAD

**Issue by makmn1** [abdoulguira/Assignments_06#1]
There is a problem when trying to deploy our site to GitHub pages. Because our index.html has to be in the public directory, GitHub won't recognize the file when it deploys our site. Instead, it will deploy the README.md file. The only places GitHub looks for index.html is in the root directory of the repository, or in a docs directory.

If we move index.html out of the public folder into the root directory or a docs folder, then it could work. The problem is that on our local machines, Create React App will throw an error if we move the index.html out of the public folder, or if we rename the public folder. This is an issue due to how Webpack works in the node-modules folder. 

The most efficient way seems to be to use the included script command "react-scripts build" to build our React application. This creates a build directory (which is defined to be ignored by git in the .gitignore directory) with 3 children files. The first is a static directory with our CSS and JS files. The second is an asset-manifest.json file. And most importantly, the third is an index.html file.

I created a branch called gh-pages. We should set GitHub pages to track the gh-pages branch and to look in the root directory. Every time we went to update our site, we should run the script above to build our site, then copy the children files of the build directory into the gh-pages branch.

Note that only the repository owner can setup GitHub pages for a repository.

**Comment by abdoulguira** [comment]
Alright Mohammed. No problem. I got you. I will then take care of setting up GitHub pages for the repositories.
I am sure I'll get it done during Lunch time tomorrow. See you tomorrow.

**Comment by abdoulguira** [comment]
Site deployed using the branch named gh-pages on the link https://abdoulguira.github.io/Assignments_06/
