### ISSUE TITLE
Take the input zipcode from the input box and do the search to look for cities. Then Display the cities in a textBox.

### ISSUE THREAD

**Issue by abdoulguira** [abdoulguira/Assignments_06#2]
Use the user input to search the ctp-zip-api given in the assignment folder. 
If the zip code is valid the API will respond with an object for each city. 
Use that response to display each city in a separate div

**Comment by makmn1** [comment]
I created 3 issues that encompass your issue, so once those three are complete we can check off this issue. Remember in the future to add your issue to the project by using the **Projects** tab to the right of this page.

**Comment by abdoulguira** [comment]
> I created 3 issues that encompass your issue, so once those three are complete we can check off this issue. Remember in the future to add your issue to the project by using the **Projects** tab to the right of this page.

no problem. Got it
